title: Luke Elson
description: Academic philosophy page
# logo: [Location of the logo]
show_downloads: false
date: October 2022
# google_analytics: [Your Google Analytics tracking ID]
# theme: jekyll-theme-cayman