project:
  type: website
  output-dir: docs

website:
  title: "Luke Elson"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching/index.qmd

format:
  html:
    css: styles.css
    toc: false



