project:
  type: website
  output-dir: docs

website:
  title: "Luke Elson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching/index.qmd
      - cv.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



