---
title: "Research"
---

Most of my published research focuses on a cluster of issues around
incomplete preferences, unsharp or imprecise credences, and value
incommensurability. In one sense of the word, two items are
*incommensurate* if neither is better but they are also not precisely
equally good. I've written a short introduction to incommensurability
on its [PhilPapers
page](https://philpapers.org/browse/incommensurability-of-value).

In more straightforwardly metaethical terrain, am interested in Global
Normative Nihilism, moral error theory's more aggressive sibling. Not
only categorical/external but also hypothetical/internal resons claims
are false. I argue that this view avoids (or embraces) 'companions in
guilt' responses to queerness arguments for the moral error theory,
and that it offers radical conceptual as well as metaphysical
simplicity. It *is* a depressing (nihilistic!) view, but I argue that
it won't lead to a complete loss of motivation or subjective concern,
as some have argued.

Despite nihilistic tendencies, I have lately also become more
interested in questions in normative or practical ethics, especially
environmental ethics.

# Publications

\(Forthcoming\) A paper on healthcare marketisation and the
introduction of risk into the doctor-patient relationship. Promised to
a *Ratio* special issue on risk.

\(Forthcoming\) 'Carbon Offsets and Shifting Harms', defending
carbon offsets against charges of injustice. Promised to an *Erasmus
Journal for Philosophy and Economics* special issue on intra- and
interpersonal dilemmas in ethics and rational choice.

\(2024\) [No Point of View Except Ours?](https://doi.org/10.1007/s11245-024-10029-8), *Topoi* 43: 479–489.
doi: 10.1007/s11245-024-10029-8  
[(pdf copy)](PDFs/point.pdf)

\(2021\) [What does incommensurability tell us about agency?](https://dx.doi.org/10.4324/9781003148012-13) in
*Value Incommensurability: Ethics, Risk, and Decision-Making*, edited by
Henrik Andersson and Anders Herlitz. Routledge.

\(2021\) [Review of *Companions in Guilt Arguments in
Metaethics*](https://ndpr.nd.edu/reviews/companions-in-guilt-arguments-in-metaethics/)
edited by Christopher Cowie and Richard Rowland, at Notre Dame
Philosophical Reviews.

\(2019\) [Probabilistic Promotion and Ability](https://quod.lib.umich.edu/e/ergo/12405314.0006.034?view=text;rgn=main), *Ergo* vol. 6, no. 34.
doi:10.3998/ergo.12405314.0006.034

\(2019\) [Can Streumer simply avoid Supervenience?](http://www.jesp.org/index.php/jesp/article/view/508), *Journal of Ethics
& Social Philosophy* vol. 16, no. 3.
doi:10.26556/jesp.v16i3.508

\(2018\) [Review of David Sobel's *From Valuing to Value*](https://academic.oup.com/analysis/article/78/3/583/5067172?guestAccessKey=084f2945-dc93-487b-a275-a76deff0fdc4), *Analysis*,
Volume 78, Issue 3, pp. 583-586. doi:10.1093/analys/any045.


\(2017\) [Incommensurability as Vagueness: a Burden-Shifting Argument](https://onlinelibrary.wiley.com/doi/10.1111/theo.12129),
*Theoria* 83: 341-363. doi: 10.1111/theo.12129  
[(preprint)](PDFs/2017-theoria-preprint.pdf)

\(2016\) [Tenenbaum and Raffaman on Vague Projects, the Self-Torturer,
and the Sorites](./PDFs/TenRaf.pdf), in *Ethics* Vol. 126, No. 2, pp. 474-488.
doi:10.1086/683533.  
[(journal page)](https://www.journals.uchicago.edu/doi/10.1086/683533)

\(2014\) [Heaps and Chains: is the Chaining Argument for Parity a
Sorites?](./PDFs/HeapsAndChains.pdf), *Ethics* Vol. 124, No. 3, pp. 557-571. doi: 10.1086/674844  
[(journal page)](https://www.journals.uchicago.edu/doi/10.1086/674844)

\(2014\) [Borderline Cases and the Collapsing Principle](./PDFs/CollapsingPrinciple.pdf), *Utilitas*
volume 26, issue 01, pp. 51-60. doi:10.1017/S095382081300023X  
[(journal page)](https://www.cambridge.org/core/journals/utilitas/article/abs/borderline-cases-and-the-collapsing-principle/C940F584A3DAA897D0CE0FAE3FEE0715)


