---
author: Luke Elson
title: Interview Handout
lang: en-GB
format:
  pdf:
    papersize: a4paper
    pdf-engine: xelatex
bibliography: ../../../zotero.bib
---

# My work and Sustainability

Environmental sustainability often involves sacrifices by many
individuals. But most individual sacrifices seem pointless.

In the past and in current work I've argued that this appearance is
not totally misleading. There is substantial *vagueness* in any
emissions targets, because we must strike a partially-arbitrary
balance between different ('incommensurate') goals.

A standard move is to regulate, by banning, limiting, or taxing walking
across the grass. “It’s a political problem not one for individuals”.

But I argue (in my forthcoming book) that the negligibility problem
recurs at the political level. This is significant because the
'negligibility' defence does often appear at a political level:

> So in developed countries, voters feel they're being asked to make
  financial sacrifices and changes in lifestyle when they know that
  their impact on global emissions is minimal. (Tony Blair, 2025).

> The UK produces only 1% of global CO2 emissions, yet China produces
  27%. China and India are building hundreds of coal-fired power
  stations. (Nigel Farage, quoted by the LSE! He's also claimed that
  UK efforts "don't make any bloody difference at all").

The challenge is to find ways to *stick with* regulations even when
times are tough. I call thmy view **climate second-bestism**; we admit
that restrictions are onerous and somewhat arbitrary. But how can they
be sustained in a democratic context?

Possibilities:

1.  Clear acknowledgement that restrictions are arbitrary and can be
    painful.

2.  Entrenching policies beyond easily revisable laws, through
    deliberative democracy and referenda.

3.  A focus on 'positive' action such as clean energy growth.

4.  Openness to 'second-best' solutions such as carbon offsetting and
    (possibly) geo-engineering.


Another line of my work going forward defends extreme skeptical views
(‘Nihilism’) in metaethics. Part of that project is a skeptical position
about the efficacy of moral thought and talk: people rarely change their
behaviour for moral reasons, and moral reasoning can engender a backlash.

# Teaching

## Courses I could contribute

My undergraduate teaching has largely focused on normative ethics and
metaethics, but also included logic and mediaeval philosophy. With
varying degrees of preparation, I could teach:

- PH103 The Big Questions: An Introduction to Philosophy

- PH111 Introduction to Logic

- PH112 Intermediate Logic and Probability

- PH201 Philosophy of Science

- PH214 Philosophy, Morals and Politics

- PH222 Philosophy and Public Policy

- PH225 Business and Organisational Ethics

- PH311 Philosophy of Economics

- PH341 Philosophy, Politics and Economics: Applications

## Topics for a Philosophy of Sustainability undergraduate course

- Defining sustainability. What is it for a system to be sustainable?

- The value of sustainability. Is it always a good thing?

- Intergenerational problems. Should the value of future people be
  discounted? Coping with the non-identity problem.

- Natural and wilderness value. Is nature valuable beyond its
  instrumental value for us?

- Ecofeminism. Is unsustainable development comparable to other forms of
  oppression?

- Carbon offsets. Even if carbon offsets are effective, are they unjust?

- Penalties. Even if excessive emissions are wrong, should they be
  criminalised?

- The inefficacy problem. How can ‘negligible’ sacrifices be motivated
  and justified?

- Carbon pessimism. Are humans or our societies ill-equipped to combat
  climate change?

# Second-Bestism Grants and Impact

My book ‘Vagueness in Action’ will be submitted to OUP for typesetting
in April. Building on chapter 6 (which concerns climate change) I will
apply for a UKRI Catalyst Award for a project ‘Entrenching Carbon Cuts’
exploring the possibilities for preventing emissions restrictions being
eroded. This is an interdisciplinary question with an empirical aspect:
how can we develop and entrench policies that meaningfully reduce carbon
emissions, without provoking backlash? What mechanisms are effective,
beyond philosophical speculation?

GSoS with its focus on realistic policy impact is a particularly
promising venue here, especially through the “mobilising political,
legal and governance systems” and “building sustainable societies”
themes. The “accelerating behaviour change” activity of the latter is
directly relevant.

# Nihilism Grants and Impact

I plan to apply for an ERC Consolidator Grant on ‘Taking Nihilism
Seriously’ at the end of 2026. This is a large ambitious application,
but my recent paper in *Ethics* provides a solid foundation.

There is impact and sustainability relevance here too: part of the
project concerns the social and psychological consequences of thinking
nothing matters. Does it make us more vulnerable to conspiracy theories
and political extremism which offer certainty and meaning? Or does it
vindicate selfishness in a way that could make our societies less
sustainable?